server:
  port: 8081

spring:
  application:
    name: desafio
    
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/desafio-dev-back-1?createDatabaseIfNotExist=true